"""metas, tramos de incentivo y objetivos

Revision ID: 300bf604a18d
Revises: f188e63250a9
Create Date: 2026-09-26 12:46:57.372313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300bf604a18d'
down_revision = 'f188e63250a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.CheckConstraint('valor > 0', name=op.f('ck_metas_valor_positivo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metas')),
    sa.UniqueConstraint('periodo', 'canal', name='uq_metas_periodo_canal')
    )
    op.create_table('tramos_incentivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cumplimiento_min', sa.Integer(), nullable=False),
    sa.Column('tasa_bp', sa.Integer(), nullable=False),
    sa.Column('bono_fijo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tramos_incentivo')),
    sa.UniqueConstraint('cumplimiento_min', name=op.f('uq_tramos_incentivo_cumplimiento_min'))
    )
    op.create_table('objetivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('saldo_inicial', sa.Integer(), nullable=True),
    sa.Column('progreso_manual', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_objetivos_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objetivos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objetivos')
    op.drop_table('tramos_incentivo')
    op.drop_table('metas')
    # ### end Alembic commands ###
