"""clientes mayoristas y lineas de venta

Revision ID: 409176b01dfe
Revises: 4a9b70ac7134
Create Date: 2026-09-30 08:13:12.602099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409176b01dfe'
down_revision = '4a9b70ac7134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('ciudad', sa.String(length=60), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes')),
    sa.UniqueConstraint('documento', name=op.f('uq_clientes_documento'))
    )
    op.create_table('lineas_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_lineas_venta_cantidad_positiva')),
    sa.CheckConstraint('precio_unitario > 0', name=op.f('ck_lineas_venta_precio_positivo')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_lineas_venta_venta_id_ventas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineas_venta'))
    )
    with op.batch_alter_table('lineas_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineas_venta_referencia'), ['referencia'], unique=False)

    with op.batch_alter_table('vendedoras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vende_mayorista', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ventas_cliente_id_clientes'), 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ventas_cliente_id_clientes'), type_='foreignkey')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('vendedoras', schema=None) as batch_op:
        batch_op.drop_column('vende_mayorista')

    with op.batch_alter_table('lineas_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineas_venta_referencia'))

    op.drop_table('lineas_venta')
    op.drop_table('clientes')
    # ### end Alembic commands ###
