"""parametros e inversion en publicidad

Revision ID: 4a9b70ac7134
Revises: 4d51daa8663b
Create Date: 2026-09-29 21:26:59.828700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9b70ac7134'
down_revision = '4d51daa8663b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inversiones_publicidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('valor_diario', sa.Integer(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.CheckConstraint('valor_diario >= 0', name=op.f('ck_inversiones_publicidad_valor_no_negativo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inversiones_publicidad')),
    sa.UniqueConstraint('mes', 'canal', name='uq_inversiones_publicidad_mes_canal')
    )
    op.create_table('parametros',
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('clave', name=op.f('pk_parametros'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametros')
    op.drop_table('inversiones_publicidad')
    # ### end Alembic commands ###
