"""medio de contacto y origen en ventas

Revision ID: 4d51daa8663b
Revises: 7cd8fcfcb695
Create Date: 2026-09-29 20:00:26.354693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d51daa8663b'
down_revision = '7cd8fcfcb695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medio_contacto', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('origen', sa.String(length=10), server_default='manual', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('origen')
        batch_op.drop_column('medio_contacto')

    # ### end Alembic commands ###
