"""liquidaciones de comisiones y esquema por vendedora

Revision ID: 72dcfc7c3c3b
Revises: 300bf604a18d
Create Date: 2026-09-26 13:06:24.367285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dcfc7c3c3b'
down_revision = '300bf604a18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedora_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fin', sa.Date(), nullable=False),
    sa.Column('ventas_netas', sa.Integer(), nullable=False),
    sa.Column('tasa_bp', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Integer(), nullable=True),
    sa.Column('comision', sa.Integer(), nullable=False),
    sa.Column('bono', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('medio_pago', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendedora_id'], ['vendedoras.id'], name=op.f('fk_liquidaciones_vendedora_id_vendedoras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidaciones')),
    sa.UniqueConstraint('vendedora_id', 'inicio', name='uq_liquidaciones_vendedora_inicio')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquidacion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_documentos_liquidacion_id_liquidaciones'), 'liquidaciones', ['liquidacion_id'], ['id'])

    with op.batch_alter_table('vendedoras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasa_comision_bp', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('meta_quincenal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bono_meta', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedoras', schema=None) as batch_op:
        batch_op.drop_column('bono_meta')
        batch_op.drop_column('meta_quincenal')
        batch_op.drop_column('tasa_comision_bp')

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documentos_liquidacion_id_liquidaciones'), type_='foreignkey')
        batch_op.drop_column('liquidacion_id')

    op.drop_table('liquidaciones')
    # ### end Alembic commands ###
