"""bitacora de cambios

Revision ID: 7cd8fcfcb695
Revises: fffcd3d04b46
Create Date: 2026-09-26 17:47:58.996132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd8fcfcb695'
down_revision = 'fffcd3d04b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('tabla', sa.String(length=40), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('cambios', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bitacora'))
    )
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitacora_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_bitacora_tabla'), ['tabla'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitacora_tabla'))
        batch_op.drop_index(batch_op.f('ix_bitacora_fecha'))

    op.drop_table('bitacora')
    # ### end Alembic commands ###
