"""pagos y aplicaciones de abonos

Revision ID: af946cbc4bbc
Revises: fe6ba8a1f925
Create Date: 2026-09-24 19:30:31.616363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af946cbc4bbc'
down_revision = 'fe6ba8a1f925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('medio', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_pagos_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos'))
    )
    op.create_table('aplicaciones_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], name=op.f('fk_aplicaciones_pago_factura_id_facturas')),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], name=op.f('fk_aplicaciones_pago_pago_id_pagos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aplicaciones_pago')),
    sa.UniqueConstraint('pago_id', 'factura_id', name='uq_aplicaciones_pago_pago_factura')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_documentos_pago_id_pagos'), 'pagos', ['pago_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documentos_pago_id_pagos'), type_='foreignkey')
        batch_op.drop_column('pago_id')

    op.drop_table('aplicaciones_pago')
    op.drop_table('pagos')
    # ### end Alembic commands ###
