"""usuarios, accesos y usuario en bitacora

Revision ID: c40da3807e12
Revises: c68bed7dc96f
Create Date: 2026-10-03 08:09:48.422514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40da3807e12'
down_revision = 'c68bed7dc96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(length=40), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=80), nullable=True),
    sa.Column('navegador', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos_acceso'))
    )
    with op.batch_alter_table('eventos_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_acceso_fecha'), ['fecha'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('totp_secreto', sa.String(length=32), nullable=True),
    sa.Column('totp_activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('version_sesion', sa.Integer(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('usuario', name=op.f('uq_usuarios_usuario'))
    )
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacora', schema=None) as batch_op:
        batch_op.drop_column('usuario')

    op.drop_table('usuarios')
    with op.batch_alter_table('eventos_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_acceso_fecha'))

    op.drop_table('eventos_acceso')
    # ### end Alembic commands ###
