"""color y talla en lineas de venta

Revision ID: c68bed7dc96f
Revises: 409176b01dfe
Create Date: 2026-10-02 21:13:51.005076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68bed7dc96f'
down_revision = '409176b01dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('talla', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas_venta', schema=None) as batch_op:
        batch_op.drop_column('talla')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
