"""clientes minoristas y autorizacion de datos

Revision ID: dbac50aa3382
Revises: c40da3807e12
Create Date: 2026-10-03 17:33:17.289487

"""
import re

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbac50aa3382'
down_revision = 'c40da3807e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_mayorista', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('autoriza_datos', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('fecha_autorizacion', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_telefono'), ['telefono'], unique=False)

    # ### end Alembic commands ###

    conexion = op.get_bind()

    # 1. Todos los clientes que existen hoy los crearon desde Mayoristas
    conexion.execute(sa.text("UPDATE clientes SET es_mayorista = 1"))

    # 2. Referencias numéricas guardadas sin el cero: '5085' -> '05085'
    conexion.execute(sa.text(
        "UPDATE lineas_venta SET referencia = substr('00000' || referencia, -5) "
        "WHERE referencia NOT GLOB '*[^0-9]*' AND length(referencia) BETWEEN 1 AND 4"
    ))

    # 3. Teléfonos de clientes al formato de 10 dígitos
    for cliente_id, telefono in conexion.execute(
            sa.text("SELECT id, telefono FROM clientes WHERE telefono IS NOT NULL")).fetchall():
        digitos = re.sub(r"\D", "", telefono)
        if len(digitos) == 12 and digitos.startswith("57"):
            digitos = digitos[2:]
        if len(digitos) == 10 and (digitos.startswith("3") or digitos.startswith("60")):
            conexion.execute(sa.text("UPDATE clientes SET telefono = :t WHERE id = :i"),
                             {"t": digitos, "i": cliente_id})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_telefono'))
        batch_op.drop_column('fecha_autorizacion')
        batch_op.drop_column('autoriza_datos')
        batch_op.drop_column('es_mayorista')

    # ### end Alembic commands ###
