"""ventas y vendedoras

Revision ID: f188e63250a9
Revises: af946cbc4bbc
Create Date: 2026-09-24 20:37:36.813389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f188e63250a9'
down_revision = 'af946cbc4bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendedoras')),
    sa.UniqueConstraint('nombre', name=op.f('uq_vendedoras_nombre'))
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('vendedora_id', sa.Integer(), nullable=True),
    sa.Column('medio_pago', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('prendas', sa.Integer(), nullable=True),
    sa.Column('es_devolucion', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint('valor > 0', name=op.f('ck_ventas_valor_positivo')),
    sa.ForeignKeyConstraint(['vendedora_id'], ['vendedoras.id'], name=op.f('fk_ventas_vendedora_id_vendedoras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas'))
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_fecha'))

    op.drop_table('ventas')
    op.drop_table('vendedoras')
    # ### end Alembic commands ###
