"""proveedores, facturas y documentos

Revision ID: fe6ba8a1f925
Revises: 
Create Date: 2026-09-22 20:36:24.277541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6ba8a1f925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores')),
    sa.UniqueConstraint('nit', name=op.f('uq_proveedores_nit')),
    sa.UniqueConstraint('nombre', name=op.f('uq_proveedores_nombre'))
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_pactada', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('iva', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.String(length=80), nullable=True),
    sa.Column('cufe', sa.String(length=120), nullable=True),
    sa.Column('pagada_contado', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_facturas_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facturas')),
    sa.UniqueConstraint('cufe', name=op.f('uq_facturas_cufe')),
    sa.UniqueConstraint('proveedor_id', 'numero', name='uq_facturas_proveedor_numero')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], name=op.f('fk_documentos_factura_id_facturas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos')),
    sa.UniqueConstraint('ruta', name=op.f('uq_documentos_ruta'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('facturas')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
