"""cuentas de dinero, gastos recurrentes y factores de temporada

Revision ID: fffcd3d04b46
Revises: 72dcfc7c3c3b
Create Date: 2026-09-26 15:29:25.132242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffcd3d04b46'
down_revision = '72dcfc7c3c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajustes_temporada',
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('factor_pct', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mes', name=op.f('pk_ajustes_temporada'))
    )
    op.create_table('cuentas_dinero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuentas_dinero')),
    sa.UniqueConstraint('nombre', name=op.f('uq_cuentas_dinero_nombre'))
    )
    op.create_table('gastos_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('frecuencia', sa.String(length=12), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('valor > 0', name=op.f('ck_gastos_recurrentes_valor_positivo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gastos_recurrentes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos_recurrentes')
    op.drop_table('cuentas_dinero')
    op.drop_table('ajustes_temporada')
    # ### end Alembic commands ###
